### ISSUE TITLE
Merge forks please and also does this need an environment.yml?

### ISSUE THREAD

**Issue by aileen-fisher** [LANL-Seismoacoustics/PyGeoTess#9]
Have a request from SMEs to install but from this fork: https://github.com/rad-lanl/PyGeoTess.  Please merge to main or open Issues for that page if that's the latest and greatest. 

Going to try installation on our DEV with miniconda3 but it wants numpy.  I'll start building an environment, but if it needs packages outside a slim base environment please update with an environment.yml.

```
(base) bash-4.2$ pip install .
Processing /data/studies/PyGS/git/PyGeoTess
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/data/studies/PyGS/git/PyGeoTess/setup.py", line 7, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by aileen-fisher** [comment]
Same or similar error when installing within the ampsuite environment:


```
(ampsuite) bash-4.2$ ls
ampsuite-main  miniconda3  PyGeoTess
(ampsuite) bash-4.2$ cd PyGeoTess/
(ampsuite) bash-4.2$ ls
CONTRIBUTING.md  docs  geotess	LICENSE.txt  README.md	setup.py  tests
(ampsuite) bash-4.2$ pip install .
Processing /data/studies/AMPSUITE/PyGeoTess
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pygeotess
  Building wheel for pygeotess (setup.py) ... error
  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [25 lines of output]
  geotess/src/GeoTessMetaData.cc: In member function 'void geotess::GeoTessMetaData::loadMetaData(geotess::IFStreamAscii&)':
  geotess/src/GeoTessMetaData.cc:968:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if (pos !=std::string::npos)
                             ^
  In file included from /data/studies/AMPSUITE/miniconda3/envs/ampsuite/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940:0,
                   from /data/studies/AMPSUITE/miniconda3/envs/ampsuite/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /data/studies/AMPSUITE/miniconda3/envs/ampsuite/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                   from geotess/src/libgeotess.cpp:1169:
  /data/studies/AMPSUITE/miniconda3/envs/ampsuite/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^
  /data/studies/AMPSUITE/miniconda3/envs/ampsuite/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!
  
          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.
  
          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************
  
  !!
    self.initialize_options()
  error: [Errno 39] Directory not empty: 'build/bdist.linux-x86_64/wheel/pygeotess-0.2.1.data/data/geotess/data'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygeotess
  Running setup.py clean for pygeotess
  error: subprocess-exited-with-error
  
  python setup.py clean did not run successfully.
  exit code: 1
  
  [1 lines of output]
  error: [Errno 13] Permission denied: 'build/bdist.linux-x86_64/wheel/pygeotess-0.2.1.data/data/geotess/data'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pygeotess
Failed to build pygeotess
ERROR: Could not build wheels for pygeotess, which is required to install pyproject.toml-based projects

```

**Comment by rad-lanl** [comment]
@aileen-fisher thank you let me look into this on my end

**Comment by jkmacc-LANL** [comment]
@aileen-fisher, @rad-lanl 's fork has been merged.  Let us know if we need to keep this Issue open.
